version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "maven"
  directories: 
    - "/"
  schedule:
    interval: "daily"
  ignore:
    - dependency-name: org.easytesting:fest-util
      versions:
        - ">= 1.1.6"