name: CI-Check-Deploy

on:
  workflow_run:
    workflows: ["CI-Tests"]
    types:
      - completed
jobs:
  checks:
    name: Dependency check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: OWASP dependency check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          OSSINDEX_API_USER: ${{ secrets.OSSINDEX_API_USER }}
          OSSINDEX_API_KEY: ${{ secrets.OSSINDEX_API_KEY }}
        run: mvn -V -B dependency-check:check
        timeout-minutes: 5
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: 
      - checks
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 11
          gpg-private-key: "${{ secrets.GPG_SIGNING_KEY }}"
          overwrite-settings: false
      - name: Deploy snapshot artifacts
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./mvnw deploy --settings .github/workflows/settings.xml -DskipTests=true -Ddependency-check.skip=true
