name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    name: License & dependency check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: OWASP dependency check
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          OSSINDEX_API_USER: ${{ secrets.OSSINDEX_API_USER }}
          OSSINDEX_API_KEY: ${{ secrets.OSSINDEX_API_KEY }}
        run: mvn -V -B dependency-check:check
        timeout-minutes: 5
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: ['17', '21']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: ${{ matrix.jdk }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: ./mvnw -B -U verify -Ddependency-check.skip=true

      - name: Running Maven GUI tests
        env:
          DISPLAY: ':99.0'
        run: |
          sudo apt-get update
          sudo apt-get install fluxbox
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          fluxbox &> ~/fluxbox.log &
          ./mvnw -B -pl '!izpack-dist' test-compile
#          ./mvnw -B verify -Pwith-gui-tests -Ddependency-check.skip=true

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: '**/target/surefire-reports/**/TEST-*.xml'
        if: always()

      - name: Archive build logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: jdk${{ matrix.jdk }}-build-logs
          retention-days: 5
          path: |
            fluxbox.log
            **/*.jfr
            **/hs_err_pid*.log
            **/target/surefire-reports/**/TEST-*.xml

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs:
     - build
     - checks
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          gpg-private-key: "${{ secrets.GPG_SIGNING_KEY }}"
          overwrite-settings: false
      - name: Deploy snapshot artifacts
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./mvnw deploy --settings .github/workflows/settings.xml -DskipTests=true -Ddependency-check.skip=true
