name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: ['11', '21']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        if: github.event_name != 'pull_request'
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          if [ -z "$NVD_API_KEY" ]; then
            echo "NVD_API_KEY is not set — skipping dependency check"
            ./mvnw -B -U verify -Ddependency-check.skip=true
          else
            echo "NVD_API_KEY is set — running full verify with dependency check"
            ./mvnw -B -U verify
          fi

      - name: Running Maven GUI tests
        run: |
          sudo apt-get update
          sudo apt-get install fluxbox
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          fluxbox &> ~/fluxbox.log &
          ./mvnw -B verify -Pwith-gui-tests -Ddependency-check.skip=true

      - name: Write out Unit Test report annotation for forked repo
        if: ${{ failure() &&  (github.event.pull_request.head.repo.full_name != github.repository) }}
        uses: mikepenz/action-junit-report@v5
        with:
          annotate_only: true # forked repo cannot write to checks so just do annotations

      - name: Archive build logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: jdk${{ matrix.jdk }}-build-logs
          retention-days: 5
          path: |
            **/*.jfr
            **/hs_err_pid*.log
            **/target/reports/*

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          gpg-private-key: "${{ secrets.GPG_SIGNING_KEY }}"
          overwrite-settings: false
      - name: Deploy snapshot artifacts
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./mvnw deploy --settings .github/workflows/settings.xml -DskipTests=true -Ddependency-check.skip=true
