name: CI-Tests
on: 
  push:
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        jdk: ['11', '21']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: ${{ matrix.jdk }}

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        if: github.event_name != 'pull_request'
        run: ./mvnw -B -U verify -D'dependency-check.skip'

      - name: Running Maven GUI tests
        env:
          DISPLAY: ':99.0'
        run: |
          sudo apt-get update
          sudo apt-get install fluxbox
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          fluxbox &> ~/fluxbox.log &
          ./mvnw -B verify -Pwith-gui-tests -D'dependency-check.skip'

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: '**/target/surefire-reports/**/TEST-*.xml'
        if: always()

      - name: Archive build logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: jdk${{ matrix.jdk }}-build-logs
          retention-days: 5
          path: |
            fluxbox.log
            **/*.jfr
            **/hs_err_pid*.log
            **/target/surefire-reports/**/TEST-*.xml